variables:
  environmentName: 'dev'
  deploymentLocation: 'eastus'

  location: 'eastus'
  environmentNameValue: 'dev'
  resourceGroupName: 'rg-aks-dev'
  aksClusterName: 'aks-dev-001'
  logAnalyticsWorkspaceName: 'law-aks-dev'
  virtualNetworkName: 'vnet-aks-dev'
  vnetAddressPrefixes: '["10.40.0.0/16"]'
  aksSubnetName: 'snet-aks-nodes'
  aksSubnetAddressPrefix: '10.40.0.0/20'
  systemNodePoolVmSize: 'Standard_D4ds_v5'
  systemNodeCount: '3'
  userNodePoolVmSize: 'Standard_D4ds_v5'
  userNodePoolMinCount: '2'
  userNodePoolMaxCount: '5'
  tags: '{"environment":"dev","costCenter":"platform","owner":"platform-team"}'
